try{var language=document.getElementsByTagName("html")[0].innerHTML.match(/OZ_jsVersion[ ]=[ ]'.*\.(.*)\.';/)[1]}catch(_error){var language="en"}var DEBUG=0;var trans;var translog="\u25a0";var transTimer;if(DEBUG)trans=function(_trans){clearTimeout(transTimer);transTimer=setTimeout(function(){translog="\u25a0"},5E3);translog+=" > "+_trans;console.log(translog)};else trans=function(_trans){};
function autopost(_element,_text,_flag,_ge,_isRecursive){try{var elm=_element;for(var i=0;i<200;i++){try{elm=elm.parentNode}catch(_error){return 0}try{if(elm.id.indexOf("update-")==0){var b=elm;break}}catch(_error){}}if(_flag==0)try{var a=_element.parentNode.parentNode}catch(_error){console.error("Google+ Extreme Button - Error : \u30b9\u30c8\u30ea\u30fc\u30e0\u3078\u306e\u8fd4\u4fe1\u306b\u5931\u6557\u3057\u307e\u3057\u305f")}else if(_flag==1){try{var reply=_element.parentNode.parentNode.parentNode.firstChild.getAttribute("oid")}catch(_error){}try{var username=
_element.parentNode.parentNode.parentNode.firstChild.innerHTML}catch(_error){}}else if(_flag==2){var post=_ge.post().elm(_element);var reply=post.userid();var username=post.auther()}var cl=b.firstChild.childNodes[1].childNodes[2].getElementsByTagName("div");for(var i=0;i<cl.length;i++)try{if(cl[i].innerHTML!="Reply to Author"){var comarea=cl[i];break}}catch(_error){}click(comarea);var d=b.getElementsByTagName("div");var e=d.length;var f=0;for(var g=0;g<e;g++)if(d[g].id.match(/.*\.editor/)){f=1;break}var commentLink;
if(f==0){a=a.parentNode.firstChild;while(1){try{a=a.nextSibling}catch(_error){break}try{if(a.getAttribute("role")=="button"){var c=document.createEvent("MouseEvents");commentLink=c;c.initEvent("click",true,false);a.dispatchEvent(c);break}}catch(_error){}}}if(_isRecursive)return;setTimeout(function(){var d=b.getElementsByTagName("div");var e=d.length;for(var f=0;f<e;f++)if(d[f].id.match(/.*\.editor/)){try{(function(_elm){var a=document.createEvent("MouseEvents");a.initEvent("click",true,false);_elm.dispatchEvent(a)})(d[f].firstChild)}catch(_error){console.error("Google+ Extreme Button - Error : .editor\u306e\u30d5\u30a9\u30fc\u30ab\u30b9\u306e\u53d6\u5f97\u306b\u5931\u6557\u3057\u307e\u3057\u305f")}try{if(_flag)if(navigator.userAgent.indexOf("Firefox")>
-1)try{d[f].firstChild.firstChild.firstChild.contentDocument.body.innerHTML="+"+reply+" <br>"}catch(_error){console.error("Google+ Extreme Button - Error : \u8fd4\u4fe1\u6642\u306e\u64cd\u4f5c\u306b\u5931\u6557\u3057\u307e\u3057\u305f")}else{if(d[f].firstChild.firstChild.innerHTML.indexOf('<button tabindex="-1" oid="'+reply+'" contenteditable="false" data-token-entity="@'+reply+'" data-sbxm="1"')==-1){(function(){var a=document.createElement("button");a.setAttribute("tabindex","-1");a.setAttribute("oid",
reply);a.setAttribute("contenteditable","false");a.setAttribute("data-token-entity","@"+reply);a.setAttribute("data-sbxm","1");a.setAttribute("style",'letter-spacing: normal;box-sizing: border-box;cursor: default;text-align: center;-webkit-box-align: center;-webkit-user-modify: read-only;white-space: nowrap;background: #EEE;border: 1px solid #DDD;-webkit-border-radius: 2px;-moz-border-radius: 2px;border-radius: 2px;display: inline-block;font: normal 13px/1.4 Arial,sans-serif;margin: 0 1px;padding: 0 1px;vertical-align: baseline;color: #36C;"><span style="color: #888;');
a.innerHTML='<span style="color: #888;">+</span>'+username+"";d[f].firstChild.firstChild.insertBefore(a,d[f].firstChild.firstChild.firstChild)})();d[f].firstChild.firstChild.innerHTML+="&nbsp;";click(d[f].firstChild.firstChild);d[f].firstChild.firstChild.blur();trans("\u81ea\u52d5\u6295\u7a3f");autopost(_element,_text,_flag,_ge,true)}}else if(navigator.userAgent.indexOf("Firefox")>-1)try{d[f].firstChild.firstChild.firstChild.contentDocument.body.innerHTML=_text+"<br>";var g=document.createEvent("KeyboardEvent");
g.initKeyEvent("keypress",true,true,window,false,false,false,false,0,13);d[f].firstChild.firstChild.firstChild.contentDocument.body.dispatchEvent(g)}catch(_error){console.error("Google+ Extreme Button - Error : \u81ea\u52d5\u30dd\u30b9\u30c8\u306b\u5931\u6557\u3057\u307e\u3057\u305f")}else try{var g=document.createEvent("TextEvent");g.initTextEvent("textInput",true,true,null,function(){return _text}());d[f].firstChild.firstChild.dispatchEvent(g);var g=document.createEvent("KeyboardEvent");g.initKeyboardEvent("keypress",
true,false,window,13,false,false,false,"",false);d[f].firstChild.firstChild.dispatchEvent(g)}catch(_error){console.error("Google+ Extreme Button - Error : \u30c6\u30ad\u30b9\u30c8\u306e\u5165\u529b\u306b\u5931\u6557\u3057\u307e\u3057\u305f")}}catch(_error){console.error("Google+ Extreme Button - Error : \u81ea\u52d5\u30dd\u30b9\u30c8\u4e2d\u306b\u4f8b\u5916\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f")}(function(elem){var ev=document.createEvent("MouseEvents");ev.initEvent("keypress",
true,true);ev.keyCode=27;elem.dispatchEvent(ev)})(d[f].firstChild.firstChild);if(_flag==0){var c=document.createEvent("MouseEvents");c.initEvent("mousedown",true,true);d[f].nextSibling.dispatchEvent(c);var c=document.createEvent("MouseEvents");c.initEvent("click",true,true);d[f].nextSibling.dispatchEvent(c);var c=document.createEvent("MouseEvents");c.initEvent("mouseup",true,true);d[f].nextSibling.dispatchEvent(c)}break}},150);return}catch(_error){console.error("Google+ Extreme Button - Error : \u81ea\u52d5\u30dd\u30b9\u30c8\u3067\u539f\u56e0\u4e0d\u660e\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f")}}
function click(_elm){try{var me=document.createEvent("MouseEvents");me.initEvent("mousedown",true,true);_elm.dispatchEvent(me)}catch(_error){}try{var me=document.createEvent("MouseEvents");me.initEvent("click",true,true);_elm.dispatchEvent(me)}catch(_error){}try{var me=document.createEvent("MouseEvents");me.initEvent("mouseup",true,true);_elm.dispatchEvent(me)}catch(_error){}}
function keysend(_elm,_str){var te=document.createEvent("TextEvent");te.initTextEvent("textInput",true,true,null,function(){return _text}());_elm.dispatchEvent(te);var te=document.createEvent("KeyboardEvent");te.initKeyboardEvent("keypress",true,false,window,null,false,false,false,8,8);_elm.dispatchEvent(te)}
function gpurlparser(_url){url=_url.replace("https://plus.google.com","");url=url.replace(/u\/\d+\//,"");if(url.slice(0,3)=="/_/"){mode=0;page="";url=url.replace("/_/","");func=url.slice(0,url.indexOf("/"));url=url.replace(/[^\/]+/,"");pos=url.indexOf("/",1);if(pos!=-1)method=url.slice(1,url.indexOf("/",1));else method=url.slice(1)}else{mode=1;func="";method="";page=url.slice(1,url.indexOf("/",1))}return[mode,func,method,page]}function _Storage(){}
_Storage.prototype.get=function(_key,_callback){chrome.extension.sendRequest({action:"get",key:_key},_callback)};_Storage.prototype.set=function(_key,_value){chrome.extension.sendRequest({action:"set",key:_key,value:_value})};_Storage.prototype.aisatsu=function(_callback){chrome.extension.sendRequest({action:"aisatsu"},_callback)};_Storage.prototype.buttonlist=function(_callback){chrome.extension.sendRequest({action:"buttonlist"},_callback)};
_Storage.prototype.settings=function(_callback){chrome.extension.sendRequest({action:"settings"},_callback)};function GpButtonApp(){}GpButtonApp.prototype.OpenFullsizeImage=function(_t,_postdata,_post,_elm){var url=_postdata[5];if(url[0]=="")return;for(var b=0;b<url.length;b++)window.open(url[b],"_blank","width="+screen.width/2+",height="+screen.width/2.66666+",scrollbars=yes")};
GpButtonApp.prototype.FullsizeDownload=function(_t,_postdata,_post,_elm){var url=_postdata[6];if(url[0]=="")return;for(var b=0;b<url.length;b++){window.open(url[b],"_blank","");window.focus()}};
GpButtonApp.prototype.tumblr=function(_t,_postdata,_post,_elm){var imgurl=encodeURIComponent(_postdata[5][0]);var url=encodeURIComponent(_postdata[3]);var body=encodeURIComponent(_postdata[2]);var name=encodeURIComponent(_postdata[1]);var time=encodeURIComponent(_postdata[4]);if(imgurl=="")window.open("http://www.tumblr.com/share?v=3&u="+url+"&t=Google%20Plus%20%28"+time+"%29%20&s="+body,"_blank","width=500,height=450,scrollbars=yes");else window.open("http://www.tumblr.com/share/photo?source="+imgurl+
"&caption=%20%3Ca%20href%3D%22"+url+"%22%3EGoogle%20Plus%20%28"+time+"%29%3C%2Fa%3E","_blank","width=500,height=450,scrollbars=yes")};
GpButtonApp.prototype.readitlater=function(_t,_postdata,_post,_elm){trans("Pocket\u306b\u767b\u9332\u3057\u307e\u3059");var a=_elm;a.removeEventListener("click",arguments.callee);if(a.className=="Read")return;var ne=document.createElement("img");ne.src=chrome.extension.getURL("button/RIL2.png");ne.className="Read";ne.style.paddingLeft="2px";ne.style.marginTop="0px";ne.style.cursor="pointer";ne.style.display="inline";ne.style.overflow="hidden";ne.style.verticalAlign="top";_elm.parentNode.replaceChild(ne,
_elm);var b=document.createElement("img");b.src="//getpocket.com/v2/r.gif?v=1&h=bf6b&rand="+Math.random()+"&u="+_postdata[3]+"&t="+_postdata[2]+" - "+_postdata[1]+" - "+"Google+ ("+_postdata[4]+")";b.style.display="none"};
GpButtonApp.prototype.evernote=function(_t,_postdata,_post,_elm){var plusone=_t.ge.post().post(_post).plusone();plusone.style.display="none";setTimeout(function(){(function(_plusone){window.addEventListener("mousedown",function(_event){removeEventListener("mousedown",arguments.callee);_plusone.style.display="block"},false)})(plusone)},1);var ra=document.createRange();ra.setStart(_post,0);ra.setEnd(_post.nextSibling,0);var gs=getSelection();gs.removeAllRanges();gs.addRange(ra)};
GpButtonApp.prototype.test=function(){alert("hello! world!")};GpButtonApp.prototype.mute=function(_t,_postdata,_post,_elm){trans("\u30df\u30e5\u30fc\u30c8\u6a5f\u80fd\u5b9f\u884c");click(_post.firstChild.firstChild.firstChild);var li=_post.getElementsByTagName("div");for(var i=0;i<li.length;i++)if(li[i].getAttribute("role")=="menu"){if(li[i].childNodes.length==4)click(li[i].firstChild.nextSibling);else if(li[i].childNodes.length==3)click(li[i].firstChild);else{click(document);alert("\u3053\u306e\u6295\u7a3f\u306f\u30df\u30e5\u30fc\u30c8\u3067\u304d\u307e\u305b\u3093")}return}};
GpButtonApp.prototype.aisatsu=function(_t,_postdata,_post,_elm){trans("\u6328\u62f6\u5b9f\u884c");var text=_postdata[2];var flag=0;for(var i=0;i<this.aisatsustr.length;i++){try{if(this.aisatsustr[i][1].indexOf("/")!=0||this.aisatsustr[i][1].indexOf("alert")!=-1||this.aisatsustr[i][1].indexOf("localStorage")!=-1||this.aisatsustr[i][1].indexOf("window")!=-1||this.aisatsustr[i][1].indexOf("document")!=-1)throw new Error;}catch(_error){continue}try{if(eval(this.aisatsustr[i][1]).test(text)){autopost(_elm,
this.aisatsustr[i][2],0);return false;flag=1;break}}catch(_error){}if(flag)break}if(flag==0)alert("\u6328\u62f6\u3059\u308b\u30e1\u30c3\u30bb\u30fc\u30b8\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3067\u3057\u305f")};GpButtonApp.prototype.aisatsustr="";function GpElements(){}
GpElements.prototype.middleElms=function(){trans("\u4e2d\u592e\u8981\u7d20\u306e\u53d6\u5f97");var contentPane=this.contentpane();var elms=contentPane.getElementsByTagName("div");for(var i=0;i<elms.length;i++)if(elms[i].getAttribute("role")=="navigation")return elms[i].nextSibling};
GpElements.prototype.myIdLink=function(){trans("Google+ID\u304c\u5165\u3063\u305f\u30ea\u30f3\u30af\u8981\u7d20\u306e\u53d6\u5f97");var middleElms=this.middleElms();var oid=middleElms.getElementsByTagName("a")[0].getAttribute("oid");return oid};GpElements.prototype.content=function(){return document.getElementById("content")};GpElements.prototype.contentpane=function(){return document.getElementById("contentPane")};
GpElements.prototype.stream=function(){try{var el=this.contentpane().getElementsByTagName("div")}catch(_error){trans("\u30b9\u30c8\u30ea\u30fc\u30e0\u306e\u53d6\u5f97\u306b\u5931\u6557\u3057\u307e\u3057\u305f");return undefined}for(var i=0;i<el.length;i++)try{if(el[i]!=undefined&&el[i].firstChild.id.indexOf("update-")==0)return el[i]}catch(_error){}return undefined};GpElements.prototype.rcolumn=function(){try{trans("\u53f3\u30ab\u30e9\u30e0\u8981\u7d20\u53d6\u5f97");return this.contentpane().nextSibling}catch(_error){}};
GpElements.prototype.lcolumn=function(){try{trans("\u5de6\u30ab\u30e9\u30e0\u8981\u7d20\u53d6\u5f97");return this.content().firstChild.firstChild}catch(_error){}};GpElements.prototype.sharebox=function(){try{var elm=this.contentpane().getElementsByTagName("div");for(var i=0;i<elm.length;i++)try{if(elm[i].id.indexOf(".f")!=-1)if(elm[i].parentNode.parentNode.parentNode.parentNode.getAttribute("guidedhelpid")=="sharebox")return elm[i]}catch(_error){}}catch(_error){}return undefined};
GpElements.prototype.sharebutton=function(){try{var elm=this.contentpane().getElementsByTagName("div");for(var i=0;i<elm.length;i++)try{if(elm[i].getAttribute("guidedhelpid")=="sharebutton")return elm[i]}catch(_error){}}catch(_error){}};
GpElements.prototype.nextbutton=function(_elm){try{var next=0;var b=_elm.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.getElementsByTagName("div");for(var i=0;i<b.length;i++)try{if(b[i].getAttribute("role")=="button"){if(next!=2){next++;continue}return b[i]}}catch(_error){}throw new Error;}catch(_error){return undefined}};GpElements.prototype.editbutton=function(_elm){try{return _elm.parentNode.parentNode.parentNode.nextSibling.getElementsByTagName("div")[1]}catch(_error){}try{return _elm.parentNode.parentNode.parentNode.parentNode.parentNode.nextSibling.nextSibling.firstChild.firstChild.nextSibling.firstChild.firstChild.firstChild.firstChild}catch(_error){}};
GpElements.prototype.commentbutton=function(_elm){try{var elm=_elm.parentNode.parentNode.parentNode.childNodes;for(var i=0;i<elm.length;i++)if(elm[i].id.indexOf(".post")!=-1)return elm[i]}catch(_error){return undefined}return undefined};GpElements.prototype.post=function(){try{return new _ElementPost}catch(_error){return undefined}};GpElements.prototype.notify=function(){try{return new _ElementNotify}catch(_error){return undefined}};function _ElementPost(){}_ElementPost.prototype.post=function(_elm){return new _SingleElementPost(_elm)};
_ElementPost.prototype.elm=function(_elm){var elm=_elm;for(var i=0;i<200;i++){try{elm=elm.parentNode}catch(_error){return 0}try{if(elm.id.indexOf("update-")==0)return new _SingleElementPost(elm)}catch(_error){}}};_ElementPost.prototype.plusoneremove=function(_postlist,_reg){try{var li=_postlist.childNodes;for(var i=0;i<li.length;i++)try{var pp=this.post(li[i]);pp.plusoneremove(_reg)}catch(_error){}}catch(_error){}};function _SingleElementPost(_elm){this.element=_elm}
_SingleElementPost.prototype.plusoneremove=function(_reg){try{var plusone=this.plusone();setTimeout(function(){var pl=plusone.childNodes;for(var ii=0;ii<pl.length;ii++){try{if(_reg.test(pl[ii].innerHTML)){plusone.removeChild(pl[ii]);break}}catch(_error){}try{if(pl[ii].getAttribute("aria-label"))if(_reg.test(pl[ii].getAttribute("aria-label"))){plusone.removeChild(pl[ii]);break}}catch(_error){}}},100)}catch(_error){}};
_SingleElementPost.prototype.image=function(){trans("\u30d5\u30eb\u30b5\u30a4\u30ba\u753b\u50cfURL\u306e\u53d6\u5f97");try{var a=this.element.getElementsByTagName("img");var b=a.length;if(b==0)return[[""],[""]];var c=0;var imageurl=new Array;var imageurl_d=new Array;imageurl[0]="";imageurl_d[0]="";for(var e=0;e<b;e++){if(a[e].getAttribute("oid"))continue;if(a[e].getAttribute("width")=="32px")continue;if(a[e].src.match(/https:\/\/lh\d*\.googleusercontent.com\/.*\/.*\/.*\/.*\/.*\/.*/)){src=a[e].src;
var dl=src.replace(/\/h\d*\//,"/s0-d/");dl=dl.replace(/\/w\d*\//,"/s0-d/");dl=dl.replace(/\/w\d*-h\d*-p\//,"/s0-d/");dl=dl.replace(/\/w\d*-h\d*\//,"/s0-d/");op=src.replace(/\/h\d*\//,"/s0/");op=op.replace(/\/w\d*\//,"/s0/");op=op.replace(/\/w\d*-h\d*-p\//,"/s0/");op=op.replace(/\/w\d*-h\d*\//,"/s0/");var flag=0;for(var ii=0;ii<imageurl.length;ii++)if(imageurl[ii]==op){flag=1;break}if(flag)continue;imageurl_d[c]=dl;imageurl[c]=op;c++}}return[imageurl,imageurl_d]}catch(_error){return[[""],[""]]}return[[""],
[""]]};_SingleElementPost.prototype.body=function(){trans("\u500b\u5225\u30dd\u30b9\u30c8\u306e\u672c\u6587\u3092\u53d6\u5f97");try{body=this.element.firstChild.firstChild.childNodes[4].firstChild.firstChild.innerHTML;body=body.replace(/<br>/g,"\n");body=body.replace(/(<wbr>|<a href="|" class=".*">|<\/a>|<b>|<\/b>|<i>|<\/i>|<span class=".*">\u7de8\u96c6<\/span>|<a class="ot-hashtag" href=".*">)/g,"");return body}catch(_error){return""}};
_SingleElementPost.prototype.auther=function(){trans("\u6295\u7a3f\u8005\u540d\u3092\u53d6\u5f97");try{var li=this.element.getElementsByTagName("a");return li[1].innerHTML}catch(_error){return""}};_SingleElementPost.prototype.permalink=function(){trans("\u500b\u5225\u30dd\u30b9\u30c8\u306e\u30d1\u30fc\u30de\u30ea\u30f3\u30af\u3092\u53d6\u5f97");try{var li=this.element.getElementsByTagName("a");for(var i=0;i<li.length;i++)try{if(li[i].href.indexOf("/posts/")!=-1)return li[i].href}catch(_error){}return""}catch(_error){return""}};
_SingleElementPost.prototype.postid=function(){trans("\u500b\u5225\u30dd\u30b9\u30c8\u306e\u30dd\u30b9\u30c8ID\u3092\u53d6\u5f97");try{return this.element.id.replace("update-","")}catch(_error){return""}};_SingleElementPost.prototype.userid=function(){try{var li=this.element.getElementsByTagName("a");for(var i=0;i<li.length;i++)try{if(li[i].getAttribute("oid"))return li[i].getAttribute("oid")}catch(_error){}}catch(_error){return""}};
_SingleElementPost.prototype.time=function(){try{var li=this.element.getElementsByTagName("a");for(var i=0;i<li.length;i++)try{if(li[i].href.indexOf("/posts/")!=-1)return li[i].title}catch(_error){}return""}catch(_error){return""}};_SingleElementPost.prototype.plusone=function(){try{var li=this.element.getElementsByTagName("div");for(var i=0;i<li.length;i++)try{if(li[i].id.indexOf("po-")==0)return li[i].parentNode}catch(_error){}throw new Error;}catch(_error){return undefined}};
_SingleElementPost.prototype._commentplusone=_commentplusone;_SingleElementPost.prototype.comment=function(){try{var elm=this.element.getElementsByTagName("span");for(var i=0;i<elm.length;i++)try{if(elm[i].getAttribute("role")=="button"&&elm[i].nextSibling.firstChild.id.indexOf("z")==0)return elm[i].nextSibling}catch(_error){}return null}catch(_error){return null}};function _ElementNotify(){}_ElementNotify.prototype.notify=function(_elm){return new _SingleElementNotify(_elm)};
_ElementNotify.prototype._notifyelement=function(){try{return document.getElementById("gbsf").contentDocument}catch(_error){}};_ElementNotify.prototype.widget=function(){try{return this._notifyelement().getElementById("notify-widget-pane").nextSibling}catch(_error){return null}};_ElementNotify.prototype.postlist=function(){try{return this.widget().childNodes[3].childNodes[2]}catch(_error){return null}};_ElementNotify.prototype.comment=function(_elm){try{return _elm.firstChild.childNodes[2].childNodes[1].childNodes[1]}catch(_error){return null}};
function _SingleElementNotify(_elm){try{this.element=_elm}catch(_error){this.element=0}}_SingleElementNotify.prototype.comment=function(){try{var elm=this.element.getElementsByTagName("span");for(var i=0;i<elm.length;i++)try{if(elm[i].getAttribute("role")=="button"&&elm[i].nextSibling.firstChild.id.indexOf("z")==0)return elm[i].nextSibling}catch(_error){}return null}catch(_error){return null}};
_SingleElementNotify.prototype.plusone=function(){try{var elm=this.element.getElementsByTagName("div");for(var i=0;i<elm.length;i++)try{if(elm[i].id.indexOf("po-")==0)return elm[i].parentNode}catch(_error){}return null}catch(_error){return null}};_SingleElementNotify.prototype._commentplusone=_commentplusone;
function _commentplusone(){try{var elm=this.element.getElementsByTagName("span");for(var i=0;i<elm.length;i++)try{if(elm[i].getAttribute("role")=="button")return elm[i]}catch(_error){}return null}catch(_error){return null}}function ElmChecker(){}ElmChecker.prototype.editor=function(_elm){try{if(_elm.id.indexOf(".f")!=-1)return true;else throw new Error;}catch(_error){return false}};
ElmChecker.prototype.post=function(_elm){try{if(/update-.+/.test(_elm.id)&&_elm.id.indexOf("#")==-1)return true;else throw new Error;}catch(_error){return false}};ElmChecker.prototype.comment=function(_elm){try{if(/z.+#\d+/.test(_elm.id))return true;else throw new Error;}catch(_error){return false}};ElmChecker.prototype.time=function(_elm){try{if(_elm.tagName=="A"&&/\/posts\//.test(_elm.href))return true;else throw new Error;}catch(_error){return false}};
ElmChecker.prototype.searchbox=function(_elm){try{if(_elm.tagName=="INPUT"&&_elm.name=="q")return true;else throw new Error;}catch(_error){return false}};
function ButtonInsert(_ge,_ga,_buttonlist,_settings){trans("\u30dc\u30bf\u30f3\u3092\u633f\u5165");this.ge=_ge;this.ga=_ga;this.buttonlist=_buttonlist;this.se=_settings;var flag=0;for(var i=0;i<this.buttonlist.length;i++){var data=this.buttonlist[i];if(data[1]){if(language=="ja"){var text=data[0][0][0];var desc=data[0][0][1]}else{var text=data[0][1][0];var desc=data[0][1][1]}if(data[2][0]==""){this.buttonelm.appendChild(this.separator.cloneNode(true));this.buttonelm.innerHTML+='<a class="Gpeb'+i+
'"><span>'+text+"</span></a>";if(data[3]!=1){this.buttonelmnoimg.appendChild(this.separator.cloneNode(true));this.buttonelmnoimg.innerHTML+='<a class="Gpeb'+i+'"><span>'+text+"</span></a>"}}else{this.buttonelm.innerHTML+='<a class="Gpeb'+i+'"><img src="'+chrome.extension.getURL("button/"+data[2][0])+'" title="'+desc+'" style="padding-left:2px;margin-top:0px;cursor: pointer;display: inline;overflow: hidden;vertical-align: top;" /></a>';if(data[3]!=1)this.buttonelmnoimg.innerHTML+='<a class="Gpeb'+
i+'"><img src="'+chrome.extension.getURL("button/"+data[2][0])+'" title="'+desc+'" style="padding-left:2px;margin-top:0px;cursor: pointer;display: inline;overflow: hidden;vertical-align: top;" /></a>'}}flag=1}}ButtonInsert.prototype.separator=document.createElement("span");ButtonInsert.prototype.separator.innerHTML="&nbsp;&nbsp;-&nbsp;&nbsp;";ButtonInsert.prototype.buttonelmnoimg=document.createElement("div");ButtonInsert.prototype.buttonelmnoimg.className="GooglePlusExtremeButton";
ButtonInsert.prototype.buttonelmnoimg.style.marginTop="12px";ButtonInsert.prototype.buttonelmnoimg.style.marginLeft="8px";ButtonInsert.prototype.buttonelmnoimg.style.display="inline-block";ButtonInsert.prototype.buttonelmnoimg.innerHTML+="";ButtonInsert.prototype.buttonelm=document.createElement("div");ButtonInsert.prototype.buttonelm.className="GooglePlusExtremeButton";ButtonInsert.prototype.buttonelm.style.marginTop="12px";ButtonInsert.prototype.buttonelm.style.marginLeft="8px";
ButtonInsert.prototype.buttonelm.style.display="inline-block";ButtonInsert.prototype.buttonelm.innerHTML+="";ButtonInsert.prototype.commentelm=document.createElement("span");ButtonInsert.prototype.commentelm.className="GpebReply";ButtonInsert.prototype.commentelm.innerHTML+="";
if(language=="ja")ButtonInsert.prototype.commentelm.innerHTML+="<a href='javascript:;'>\u8fd4\u4fe1</a>";else if(language=="zh_CN")ButtonInsert.prototype.commentelm.innerHTML+="<a href='javascript:;'>\u56de\u590d</a>";else if(language=="zh_TW")ButtonInsert.prototype.commentelm.innerHTML+="<a href='javascript:;'>\u56de\u8986</a>";else ButtonInsert.prototype.commentelm.innerHTML+="<a href='javascript:;'>Reply</a>";ButtonInsert.prototype.replyelm=document.createElement("div");
ButtonInsert.prototype.replyelm.className="GpebReply";ButtonInsert.prototype.replyelm.style.display="inline-block";ButtonInsert.prototype.replyelm.style.marginTop="12px";ButtonInsert.prototype.replyelm.innerHTML+="&nbsp;&nbsp;-&nbsp;&nbsp;";
if(language=="ja")ButtonInsert.prototype.replyelm.innerHTML+="<a>\u8fd4\u4fe1</a>";else if(language=="zh_CN")ButtonInsert.prototype.replyelm.innerHTML+="<a>\u56de\u590d</a>";else if(language=="zh_TW")ButtonInsert.prototype.replyelm.innerHTML+="<a>\u56de\u8986</a>";else ButtonInsert.prototype.replyelm.innerHTML+="<a>Reply</a>";
ButtonInsert.prototype.all=function(_elm){try{var elm=_elm.childNodes;for(var i=0;i<elm.length;i++){var pl=this.ge.post().post(elm[i]).plusone();try{var pe=pl.getElementsByTagName("div");var flag=0;for(var ii=0;ii<pe.length;ii++)try{if(pe[ii].className=="GooglePlusExtremeButton"){flag=1;break}}catch(_error){}if(flag==0)try{this.post(elm[i])}catch(_error){}}catch(_error){}}}catch(_error){}};
ButtonInsert.prototype.post=function(_elm){var pp=this.ge.post().post(_elm);var plusone=pp.plusone();if(!plusone)return;try{var pl=plusone.getElementsByTagName("div");for(var i=0;i<pl.length;i++)if(pl[i].className=="GooglePlusExtremeButton")return}catch(_error){}plusone.style.whiteSpace="nowrap";try{var pc=plusone.childNodes;for(var i=0;i<pc.length;i++)if(pc[i].tagName="DIV"&&pc[i].getAttribute("role")=="button"){pc[i].style.display="inline-block";if(pc[i].childNodes.length==0)pc[i].style.height=
"22px";pc[i].style.overflow="visible"}}catch(_error){}var li=plusone.getElementsByTagName("div");try{if(pp.image()[0]=="")plusone.insertBefore(this.buttonelmnoimg.cloneNode(true),plusone.lastChild);else plusone.insertBefore(this.buttonelm.cloneNode(true),plusone.lastChild)}catch(_error){}if(this.se[0])try{plusone.insertBefore(this.replyelm.cloneNode(true),plusone.lastChild);for(var i=0;i<li.length;i++)try{if(li[i].className=="GpebReply"){(function(_ge){li[i].addEventListener("click",function(_event){autopost(_event.target,
"",2,_ge);return false},false)})(this.ge);break}}catch(_error){}}catch(_error){}try{for(var i=0;i<li.length;i++)try{if(li[i].className=="GooglePlusExtremeButton"){var gp=li[i].getElementsByTagName("a");for(var ii=0;ii<gp.length;ii++)for(var iii=0;iii<this.buttonlist.length;iii++)try{if(gp[ii].className=="Gpeb"+iii){var data=this.buttonlist[iii];try{if(data[4][0])(function(_elm,_t,_appname){_elm.addEventListener("click",function(_event){var elm=_event.target;var post=_t.ge.post().elm(_elm);var image=
post.image();var postdata=[post.userid(),post.auther(),post.body(),post.permalink(),post.time(),image[0],image[1]];eval("_t.ga."+_appname+"(_t, postdata, post.element, elm);")},false)})(gp[ii],this,data[4][0]);else if(data[4][1])(function(_elm,_text){_elm.addEventListener("click",function(_event){autopost(_event.target,_text,0);return false},false)})(gp[ii],data[4][1]);else if(data[4][2][0])(function(_elm,_t,_url,_x,_y){_elm.addEventListener("click",function(_event){var elm=_event.target;var post=
_t.ge.post().elm(_elm);url=_url.replace(/<URL>/g,encodeURIComponent(post.permalink()));url=url.replace(/<BODY>/g,encodeURIComponent(post.body()));url=url.replace(/<NAME>/g,encodeURIComponent(post.auther()));url=url.replace(/<USERID>/g,encodeURIComponent(post.userid()));url=url.replace(/<TIME>/g,encodeURIComponent(post.time()));var image=post.image();url=url.replace(/<IMG>/g,encodeURIComponent(image[0][0]));post.time().match(/(^.*)[ ]/);url=url.replace(/<TIME2>/g,encodeURIComponent(RegExp.$1));url=
url.replace(/<ACTIVITY>/g,post.postid());if(_x!=0||_y!=0)window.open(url,"_blank","width="+_x+",height="+_y+",scrollbars=yes");else window.open(url,"_blank","")},false)})(gp[ii],this,data[4][2][0],data[4][2][1],data[4][2][2])}catch(_error){}}}catch(_error){}break}}catch(_error){}}catch(_error){}if(this.se[1])try{var comment=this.ge.post().post(_elm).comment().childNodes;for(var i=0;i<comment.length;i++){var spanlist=comment[i].getElementsByTagName("span");var flag=0;for(var ii=0;ii<spanlist.length;ii++)try{if(spanlist[ii].className==
"GpebReply"){flag=1;break}}catch(_error){}if(flag)break;this.postcomment(comment[i])}}catch(_error){}};
ButtonInsert.prototype.notify=function(_elm){var nt=this.ge.notify().notify(_elm);var plusone=nt.plusone();if(plusone==null)return;try{var pl=plusone.getElementsByTagName("div");for(var i=0;i<pl.length;i++)if(pl[i].className=="GpebReply")return}catch(_error){}if(this.se[0])try{plusone.insertBefore(this.replyelm.cloneNode(true),plusone.lastChild);if(plusone.lastChild.childNodes.length==0)plusone.lastChild.style.display="none";var li=plusone.getElementsByTagName("div");for(var i=0;i<li.length;i++)try{if(li[i].className==
"GpebReply"){(function(_ge){li[i].addEventListener("click",function(_event){autopost(_event.target,"",2,_ge);return false},false)})(this.ge);break}}catch(_error){}}catch(_error){}};
ButtonInsert.prototype.notifycomment=function(_elm){var t=this;trans("\u6307\u5b9a\u3057\u305f\u30b3\u30e1\u30f3\u30c8\u6b04\u306b\u8981\u7d20\u3092\u8ffd\u52a0");(function(){var count=0;var tid=setInterval(function(){if(count==100)console.error("\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f");var mouseover=t.ge.notify().notify(_elm)._commentplusone();if(!mouseover)return false;var bl=mouseover.getElementsByTagName("span");if(bl.length||count==10){clearInterval(tid);try{for(var i=0;i<
bl.length;i++)try{if(bl[i].className=="GpebReply"){clearInterval(tid);return true}}catch(_error){}if(t.se[1]){trans("\u81ea\u5206\u306eID\u3092\u53d6\u5f97");var myId=t.ge.__proto__.myIdLink();if(myId==mouseover.parentNode.parentNode.getElementsByTagName("a")[0].getAttribute("oid")){trans("\u81ea\u5206\u306e\u6295\u7a3f\u306b\u306f\u8fd4\u4fe1\u30dc\u30bf\u30f3\u3092\u3064\u3051\u307e\u305b\u3093");clearInterval(tid);return}mouseover.innerHTML="";mouseover.appendChild(t.commentelm.cloneNode(true));
var bl=mouseover.getElementsByTagName("span");for(var i=0;i<bl.length;i++)try{if(bl[i].className=="GpebReply"){bl[i].addEventListener("click",function(_event){autopost(mouseover.firstChild,"",1);return false},false);break}}catch(_error){}}clearInterval(tid);return true}catch(_error){return false}}count++},10)})()};
ButtonInsert.prototype.postcomment=function(_elm){trans("\u6307\u5b9a\u3057\u305f\u30b3\u30e1\u30f3\u30c8\u6b04\u306b\u8981\u7d20\u3092\u8ffd\u52a0");try{var mouseover=this.ge.post().post(_elm)._commentplusone();if(!mouseover)return false;if(this.se[1]){var flag=1;var bl=mouseover.getElementsByTagName("span");for(var i=0;i<bl.length;i++)try{if(bl[i].className=="GpebReply")flag=0}catch(_error){}if(flag){var myId=t.ge.__proto__.myIdLink();if(myId==mouseover.parentNode.parentNode.getElementsByTagName("a")[0].getAttribute("oid")){trans("\u81ea\u5206\u306e\u6295\u7a3f\u306b\u306f\u8fd4\u4fe1\u30dc\u30bf\u30f3\u3092\u3064\u3051\u307e\u305b\u3093");
return true}mouseover.innerHTML="";mouseover.appendChild(this.commentelm.cloneNode(true));var bl=mouseover.getElementsByTagName("span");for(var i=0;i<bl.length;i++)try{if(bl[i].className=="GpebReply"){bl[i].addEventListener("click",function(_event){autopost(mouseover.firstChild,"",1);return false},false);break}}catch(_error){}}}return true}catch(_error){return false}};function GpActive(){}GpActive.prototype.active=true;
function GpEvent(_ge,_ec,_bi,_settings){this.ge=_ge;this.ec=_ec;this.bi=_bi;this.se=_settings}GpEvent.prototype.elmflag=0;GpEvent.prototype.notifyelmflag=0;GpEvent.prototype.notifyelmflag2=0;
GpEvent.prototype.dom=function(_active){var t=this;var nt=t.ge.notify();var po=t.ge.post();var contentpane=this.ge.contentpane();document.addEventListener("DOMNodeInserted",function(_event){var elm=_event.target;if(t.ec.comment(elm))(function(){var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:1");return}if(t.bi.postcomment(elm))clearInterval(tid);count++},100)})();if(t.ec.time(elm)){var post=
po.elm(elm).element;t.bi.post(post);if(t.se[2])t.ge.post().post(post).plusoneremove(/\u3053\u306e\u6295\u7a3f\u306e\u30a2\u30af\u30c6\u30a3\u30d3\u30c6\u30a3|Activity[ ]on[ ]this[ ]post|\u95dc\u65bc\u9019\u5247\u8a0a\u606f\u7684\u6d3b\u52d5/);try{if(t.se[5]){var scsize=document.documentElement.scrollTop||document.body.scrollTop;if(scsize<=100||_active.active==false){var gs=t.ge.stream();var pl=gs.childNodes;while(1)if(pl.length>=50)gs.removeChild(gs.lastChild);else break}}}catch(_error){}}if(nt.widget()){if(notifyelmflag==
0){notifyelmflag=1;var elm=nt.widget();elm.addEventListener("DOMNodeInserted",function(_event){if(notifyelmflag2==1){var elm=_event.target;if(t.ec.post(elm))(function(_elm){var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:2");return}try{t.bi.notify(_elm)}catch(_error){}if(t.se[1])try{var ci=nt.comment(_elm).childNodes;var ce=ci.length;for(var i=0;i<ce;i++)try{t.bi.notifycomment(ci[i])}catch(_error){}clearInterval(tid)}catch(_error){}count++},
100)})(elm)}if(t.ec.comment(elm))t.bi.notifycomment(elm);if(notifyelmflag2==0){notifyelmflag2=1;try{var li=nt.postlist().childNodes;try{for(var i=0;i<li.length;i++){t.bi.notify(li[i]);try{var ci=nt.notify(li[i]).comment().childNodes;var ce=ci.length;for(var j=0;j<ce;j++)t.bi.notifycomment(ci[j])}catch(_error){}}}catch(_error){}}catch(_error){}}},false)}}else{notifyelmflag=0;notifyelmflag2=0}if(t.elmflag==0){t.elmflag=1;(function(){var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:5");
return}var li=t.ge.stream();try{if(li.firstChild){clearInterval(tid);t.bi.all(li);if(t.se[2])po.plusoneremove(li,/\u3053\u306e\u6295\u7a3f\u306e\u30a2\u30af\u30c6\u30a3\u30d3\u30c6\u30a3|Activity[ ]on[ ]this[ ]post|\u95dc\u65bc\u9019\u5247\u8a0a\u606f\u7684\u6d3b\u52d5/)}}catch(_error){}count++},100)})()}},false)};
GpEvent.prototype.key=function(){var t=this;document.addEventListener("keydown",function(_event){var elm=_event.target;var key=_event.keyCode;var shiftkey=_event.shiftKey;var ctrlkey=_event.ctrlKey;var cmdkey=_event.metaKey;if(t.ec.editor(elm)){if(DEBUG)trans("\u30a8\u30c7\u30a3\u30bf");if(DEBUG)trans("\u6295\u7a3f\u753b\u9762\u3092\u53d6\u5f97");if(elm===t.ge.sharebox()){if(DEBUG)trans("\u6295\u7a3f\u753b\u9762");if(key==9){if(DEBUG)trans("\u6295\u7a3f\u753b\u9762\u306e\u30a8\u30c7\u30a3\u30bf\u3067TAB\u30ad\u30fc\u3092\u62bc\u4e0b");
setTimeout(function(){if(t.se[4])try{if(DEBUG)trans("\u6295\u7a3f\u30dc\u30bf\u30f3\u306e\u30d5\u30a9\u30fc\u30ab\u30b9");t.ge.sharebutton().focus()}catch(_error){}},1)}else if(key==13)if(shiftkey||cmdkey||ctrlkey)if(t.se[3]){if(DEBUG){trans("\u901a\u5e38\u306eShift+Enter\u3067\u6295\u7a3f");trans("\u30af\u30ea\u30c3\u30af");trans("\u5171\u6709\u30dc\u30bf\u30f3")}click(t.ge.sharebutton());setTimeout(function(){click(t.ge.sharebutton());if(DEBUG)trans("\u9045\u5ef6\u6295\u7a3f\u6a5f\u80fd\u3092\u5b9f\u884c");
setTimeout(function(){click(t.ge.sharebutton())},100);setTimeout(function(){click(t.ge.sharebutton())},200);setTimeout(function(){click(t.ge.sharebutton())},300);setTimeout(function(){click(t.ge.sharebutton())},400);setTimeout(function(){click(t.ge.sharebutton())},500);setTimeout(function(){click(t.ge.sharebutton())},600);setTimeout(function(){click(t.ge.sharebutton())},700)},10)}}else{if(DEBUG)trans("\u30dd\u30b9\u30c8\u3068\u5171\u6709\u30dc\u30bf\u30f3\u4ee5\u5916");if(key==13){if(shiftkey||cmdkey||
ctrlkey){if(DEBUG)trans("\u30b7\u30d5\u30c8\u30ad\u30fc\u3001\u30b3\u30de\u30f3\u30c9\u30ad\u30fc\u3001\u30b3\u30f3\u30c8\u30ed\u30fc\u30eb\u30ad\u30fc\u304c\u62bc\u4e0b");try{if(t.se[3]){if(DEBUG)trans("\u30b3\u30e1\u30f3\u30c8\u6b04\u3092Shift+Enter\u3067\u6295\u7a3f");try{var buttonelm=t.ge.commentbutton(elm);trans("\u30b3\u30e1\u30f3\u30c8\u6b04\u306e\u30a8\u30ec\u30e1\u30f3\u30c8");if(buttonelm==undefined)throw new Error;click(buttonelm);return}catch(_error){}trans("\u518d\u5171\u6709\u306e\u4fdd\u5b58\u30dc\u30bf\u30f3\u306e\u30a8\u30ec\u30e1\u30f3\u30c8\u3092\u53d6\u5f97\u3057\u307e\u3059");
try{var buttonelm=t.ge.nextbutton(elm);if(buttonelm==undefined)throw new Error;click(buttonelm);return}catch(_error){}}}catch(_error){}}}else if(key==9){if(DEBUG)trans("TAB\u30ad\u30fc\u304c\u62bc\u3055\u308c\u307e\u3057\u305f");setTimeout(function(){if(t.se[4]){try{if(elm.parentNode.parentNode.nextSibling.id.indexOf(".post")!=-1){if(DEBUG)trans("\u6295\u7a3f\u30dc\u30bf\u30f3\u3060\u3063\u305f\u305f\u3081\u30b9\u30eb\u30fc\u3057\u307e\u3057\u305f\u3002");return}}catch(_error){}try{if(DEBUG)trans("\u30a8\u30c7\u30a3\u30bf\u30dc\u30bf\u30f3\u306b\u30d5\u30a9\u30fc\u30ab\u30b9\u3092\u5408\u308f\u305b\u307e\u3057\u305f");
trans(elm);trans(t.ge.editbutton(elm));t.ge.editbutton(elm).focus();return}catch(_error){}try{if(DEBUG)trans("\u6b21\u306e\u30dc\u30bf\u30f3\u306b\u30d5\u30a9\u30fc\u30ab\u30b9\u3092\u5408\u308f\u305b\u307e\u3057\u305f");t.ge.nextbutton(elm).focus();return}catch(_error){}}},1)}}}else if(elm==t.ge.sharebutton()){if(key==9)if(t.se[4])setTimeout(function(){try{trans("\u30d5\u30a9\u30fc\u30ab\u30b9\u3092\u30a8\u30c7\u30a3\u30bf\u306b\u623b\u3057\u307e\u3059");t.ge.sharebox().focus()}catch(_error){}},
1)}else if(t.ec.searchbox(elm))if(key==13)(function(){setTimeout(function(){var count=0;var tid=setInterval(function(){var li=t.ge.stream();try{if(li.firstChild){t.bi.all(li);if(t.se[2])po.plusoneremove(li,/\u3053\u306e\u6295\u7a3f\u306e\u30a2\u30af\u30c6\u30a3\u30d3\u30c6\u30a3|Activity[ ]on[ ]this[ ]post|\u95dc\u65bc\u9019\u5247\u8a0a\u606f\u7684\u6d3b\u52d5/);clearInterval(tid)}}catch(_error){if(count==100)clearInterval(tid);count++}},100)},3E3)})()},false);(function(){var nt=t.ge.notify();var count=
0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:6");return}var widget=nt.widget();if(widget){trans(widget);widget.addEventListener("keydown",function(_event){var elm=_event.target;var key=_event.keyCode;var shiftkey=_event.shiftKey;var cmdkey=_event.metaKey;if(key==13)if(shiftkey||cmdkey)try{if(t.se[3])click(t.ge.commentbutton(elm))}catch(_error){}if(key==37||key==39)(function(){var count=
0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:7");return}try{var li=nt.postlist().childNodes;try{for(var i=0;i<li.length;i++){try{t.bi.notify(li[i])}catch(_error){}if(t.se[1])try{var pn=nt.notify(li[i]);var ci=pn.comment().childNodes;var ce=ci.length;for(var j=0;j<ce;j++)t.bi.notifycomment(ci[j])}catch(_error){}}}catch(_error){}clearInterval(tid)}catch(_error){}count++},100)})()},false);
clearInterval(tid)}count++},100)})()};
GpEvent.prototype.click=function(){t=this;var nt=t.ge.notify();var po=t.ge.post();document.addEventListener("click",function(_event){var elm=_event.target;var flag=0;try{if(elm.tagName=="A")flag=1}catch(_error){}try{if(elm.getAttribute("data-tooltip"))flag=1}catch(_error){}try{if(elm.getAttribute("aria-label"))flag=1}catch(_error){}try{if(elm.className=="GooglePlusExtremeButton")flag=0}catch(_error){}try{if(elm.parentNode.className=="GpebReply")flag=0}catch(_error){}if(flag)(function(){setTimeout(function(){var count=0;
var tid=setInterval(function(){var li=t.ge.stream();try{if(li.firstChild){t.bi.all(li);if(t.se[2])po.plusoneremove(li,/\u3053\u306e\u6295\u7a3f\u306e\u30a2\u30af\u30c6\u30a3\u30d3\u30c6\u30a3|Activity[ ]on[ ]this[ ]post|\u95dc\u65bc\u9019\u5247\u8a0a\u606f\u7684\u6d3b\u52d5/);clearInterval(tid)}}catch(_error){if(count==100)clearInterval(tid);count++}},100)},2E3)})()},false);(function(){var nt=t.ge.notify();var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:8");
return}var widget=nt.widget();if(widget){widget.addEventListener("click",function(_event){var elm=_event.target;(function(){var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:9");return}try{var li=nt.postlist().childNodes;trans("nt.postlist()",nt.postlist());try{for(var i=0;i<li.length;i++){if(t.se[0])try{t.bi.notify(li[i])}catch(_error){}if(t.se[1])try{var pn=nt.notify(li[i]);var ci=
pn.comment().childNodes;var ce=ci.length;for(var j=0;j<ce;j++)t.bi.notifycomment(ci[j])}catch(_error){}}}catch(_error){}clearInterval(tid)}catch(_error){}count++},100)})()},false);clearInterval(tid)}count++},100)})()};
GpEvent.prototype.page=function(){var t=this;var po=t.ge.post();window.addEventListener("__internalGRPEvent",function(_event){var count=0;var tid=setInterval(function(){try{var li=t.ge.stream();if(li.firstChild){t.bi.all(li);if(t.se[2])po.plusoneremove(li,/\u3053\u306e\u6295\u7a3f\u306e\u30a2\u30af\u30c6\u30a3\u30d3\u30c6\u30a3|Activity[ ]on[ ]this[ ]post|\u95dc\u65bc\u9019\u5247\u8a0a\u606f\u7684\u6d3b\u52d5/);clearInterval(tid)}}catch(_error){if(count==100)clearInterval(tid);count++}},100)},false)};
GpEvent.prototype.active=function(_active){window.addEventListener("focus",function(_event){_active.active=true},false);window.addEventListener("blur",function(_event){_active.active=false},false)};
function main(){var gl=location.href;function gp(){}gp.r=gpurlparser(gl);gp.mode=gp.r[0];gp.func=gp.r[1];gp.method=gp.r[2];gp.page=gp.r[3];if(gp.mode&&gp.page!="hangouts"&&gp.page!="talkgadget"&&gp.func!="apps-static"&&gp.func!="notifications"){var storage=new _Storage;var settings;storage.get("GooglePlusExtremeButton.settings",function(_response){var settingsstr=_response;if(settingsstr)try{settings=JSON.parse(settingsstr)}catch(_error){alert("Google+ Extreme Button \u306e \u8a2d\u5b9a\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f");
return}else storage.settings(function(_response){settings=_response;storage.set("GooglePlusExtremeButton.settings",JSON.stringify(settings))})});var buttonlist;storage.get("GooglePlusExtremeButton.buttonlist",function(_response){var buttonliststr=_response;if(buttonliststr)try{buttonlist=JSON.parse(buttonliststr)}catch(_error){alert("Google+ Extreme Button \u306e \u30dc\u30bf\u30f3\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f");return}else storage.buttonlist(function(_response){buttonlist=
_response;storage.set("GooglePlusExtremeButton.buttonlist",JSON.stringify(buttonlist))})});var elmflag=0;var ge=new GpElements;var ec=new ElmChecker;var ga=new GpButtonApp;storage.get("GooglePlusExtremeButton.aisatsu",function(_response){var aisatsustr=_response;if(aisatsustr)try{ga.aisatsustr=JSON.parse(aisatsustr)}catch(_error){alert("Google+ Extreme Button \u306e \u6328\u62f6\u30c7\u30fc\u30bf\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f");return}else storage.aisatsu(function(_response){ga.aisatsustr=
_response;storage.set("GooglePlusExtremeButton.aisatsu",JSON.stringify(ga.aisatsustr))})});function checkBool(val){if(val)return"true";else return"false"}(function(){var count=0;var tid=setInterval(function(){if(count==100){if(DEBUG)console.error("Google+ Extreme Button - \u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f ID:10");return}if(buttonlist&&ga.aisatsustr&&settings){clearInterval(tid);var gac=new GpActive;var bi=new ButtonInsert(ge,ga,buttonlist,settings);var Gv=new GpEvent(ge,
ec,bi,settings);Gv.dom(gac);Gv.page();Gv.key();Gv.click();Gv.active(gac)}count++},100)})()}}main();